# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 21) do

  create_table "episodes", :force => true do |t|
    t.column "episode_date", :datetime, :null => false
    t.column "show_id", :integer
    t.column "season_number", :integer
    t.column "episode_number", :integer
  end

  create_table "feed_source_data", :force => true do |t|
    t.column "feed_source_id", :integer
    t.column "url", :string
  end

  create_table "shows", :force => true do |t|
    t.column "title", :string
    t.column "short_name", :string
  end

  create_table "sources", :force => true do |t|
    t.column "type", :string
    t.column "show_id", :integer
    t.column "update_interval", :integer
    t.column "child_id", :integer
  end

  create_table "torrents", :force => true do |t|
    t.column "date_added", :datetime, :null => false
    t.column "title", :string, :default => "", :null => false
    t.column "size", :integer, :limit => 9
    t.column "url", :string, :default => "", :null => false
    t.column "num", :integer, :limit => 6, :default => 0, :null => false
    t.column "episode_id", :integer
  end

  create_table "tvrage_episodes", :force => true do |t|
    t.column "number", :integer
    t.column "short_name", :string
    t.column "season_number", :integer
    t.column "episode_number", :integer
    t.column "date", :date
    t.column "title", :string
    t.column "url", :string
    t.column "show_id", :integer
    t.column "episode_id", :integer
  end

  create_table "tvrage_shows", :force => true do |t|
    t.column "show_name", :string
    t.column "show_url", :string
    t.column "show_id", :integer
  end

  create_table "updates", :force => true do |t|
    t.column "source_id", :integer
    t.column "time", :datetime
    t.column "result", :integer
  end

end
